// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uprotocol_options.proto

#include "uprotocol_options.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace uprotocol {
}  // namespace uprotocol
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_uprotocol_5foptions_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_uprotocol_5foptions_2eproto = nullptr;
const uint32_t TableStruct_uprotocol_5foptions_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_uprotocol_5foptions_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027uprotocol_options.proto\022\tuprotocol\032 go"
  "ogle/protobuf/descriptor.proto:/\n\004name\022\037"
  ".google.protobuf.ServiceOptions\030\264\207\003 \001(\t:"
  "8\n\rversion_major\022\037.google.protobuf.Servi"
  "ceOptions\030\265\207\003 \001(\r:8\n\rversion_minor\022\037.goo"
  "gle.protobuf.ServiceOptions\030\266\207\003 \001(\r:-\n\002i"
  "d\022\037.google.protobuf.ServiceOptions\030\267\207\003 \001"
  "(\r:;\n\020permission_level\022\037.google.protobuf"
  ".ServiceOptions\030\270\207\003 \001(\r:6\n\tmethod_id\022\036.g"
  "oogle.protobuf.MethodOptions\030\230\210\003 \001(\r\210\001\001:"
  "A\n\027method_permission_level\022\036.google.prot"
  "obuf.MethodOptions\030\231\210\003 \001(\r:;\n\rbase_topic"
  "_id\022\037.google.protobuf.MessageOptions\030\374\210\003"
  " \001(\r\210\001\001:A\n\026topic_permission_level\022\037.goog"
  "le.protobuf.MessageOptions\030\375\210\003 \001(\r:>\n\022re"
  "source_name_mask\022\035.google.protobuf.Field"
  "Options\030\340\211\003 \001(\t\210\001\001B\031\n\025org.eclipse.uproto"
  "colP\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_uprotocol_5foptions_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::_pbi::once_flag descriptor_table_uprotocol_5foptions_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_uprotocol_5foptions_2eproto = {
    false, false, 693, descriptor_table_protodef_uprotocol_5foptions_2eproto,
    "uprotocol_options.proto",
    &descriptor_table_uprotocol_5foptions_2eproto_once, descriptor_table_uprotocol_5foptions_2eproto_deps, 1, 0,
    schemas, file_default_instances, TableStruct_uprotocol_5foptions_2eproto::offsets,
    nullptr, file_level_enum_descriptors_uprotocol_5foptions_2eproto,
    file_level_service_descriptors_uprotocol_5foptions_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_uprotocol_5foptions_2eproto_getter() {
  return &descriptor_table_uprotocol_5foptions_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_uprotocol_5foptions_2eproto(&descriptor_table_uprotocol_5foptions_2eproto);
namespace uprotocol {
const std::string name_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::ServiceOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  name(kNameFieldNumber, name_default, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::ServiceOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< uint32_t >, 13, false>
  version_major(kVersionMajorFieldNumber, 0u, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::ServiceOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< uint32_t >, 13, false>
  version_minor(kVersionMinorFieldNumber, 0u, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::ServiceOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< uint32_t >, 13, false>
  id(kIdFieldNumber, 0u, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::ServiceOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< uint32_t >, 13, false>
  permission_level(kPermissionLevelFieldNumber, 0u, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< uint32_t >, 13, false>
  method_id(kMethodIdFieldNumber, 0u, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< uint32_t >, 13, false>
  method_permission_level(kMethodPermissionLevelFieldNumber, 0u, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< uint32_t >, 13, false>
  base_topic_id(kBaseTopicIdFieldNumber, 0u, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< uint32_t >, 13, false>
  topic_permission_level(kTopicPermissionLevelFieldNumber, 0u, nullptr);
const std::string resource_name_mask_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  resource_name_mask(kResourceNameMaskFieldNumber, resource_name_mask_default, nullptr);

// @@protoc_insertion_point(namespace_scope)
}  // namespace uprotocol
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
