// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ustatus.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ustatus_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ustatus_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ustatus_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ustatus_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ustatus_2eproto;
namespace uprotocol {
namespace v1 {
class UStatus;
struct UStatusDefaultTypeInternal;
extern UStatusDefaultTypeInternal _UStatus_default_instance_;
}  // namespace v1
}  // namespace uprotocol
PROTOBUF_NAMESPACE_OPEN
template<> ::uprotocol::v1::UStatus* Arena::CreateMaybeMessage<::uprotocol::v1::UStatus>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace uprotocol {
namespace v1 {

enum UCode : int {
  OK = 0,
  CANCELLED = 1,
  UNKNOWN = 2,
  INVALID_ARGUMENT = 3,
  DEADLINE_EXCEEDED = 4,
  NOT_FOUND = 5,
  ALREADY_EXISTS = 6,
  PERMISSION_DENIED = 7,
  UNAUTHENTICATED = 16,
  RESOURCE_EXHAUSTED = 8,
  FAILED_PRECONDITION = 9,
  ABORTED = 10,
  OUT_OF_RANGE = 11,
  UNIMPLEMENTED = 12,
  INTERNAL = 13,
  UNAVAILABLE = 14,
  DATA_LOSS = 15,
  UCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  UCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool UCode_IsValid(int value);
constexpr UCode UCode_MIN = OK;
constexpr UCode UCode_MAX = UNAUTHENTICATED;
constexpr int UCode_ARRAYSIZE = UCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* UCode_descriptor();
template<typename T>
inline const std::string& UCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, UCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function UCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    UCode_descriptor(), enum_t_value);
}
inline bool UCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, UCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<UCode>(
    UCode_descriptor(), name, value);
}
// ===================================================================

class UStatus final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:uprotocol.v1.UStatus) */ {
 public:
  inline UStatus() : UStatus(nullptr) {}
  ~UStatus() override;
  explicit PROTOBUF_CONSTEXPR UStatus(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UStatus(const UStatus& from);
  UStatus(UStatus&& from) noexcept
    : UStatus() {
    *this = ::std::move(from);
  }

  inline UStatus& operator=(const UStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline UStatus& operator=(UStatus&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const UStatus* internal_default_instance() {
    return reinterpret_cast<const UStatus*>(
               &_UStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UStatus& a, UStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(UStatus* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UStatus>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UStatus& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UStatus& from) {
    UStatus::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UStatus* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "uprotocol.v1.UStatus";
  }
  protected:
  explicit UStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDetailsFieldNumber = 3,
    kMessageFieldNumber = 2,
    kCodeFieldNumber = 1,
  };
  // repeated .google.protobuf.Any details = 3;
  int details_size() const;
  private:
  int _internal_details_size() const;
  public:
  void clear_details();
  ::PROTOBUF_NAMESPACE_ID::Any* mutable_details(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PROTOBUF_NAMESPACE_ID::Any >*
      mutable_details();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Any& _internal_details(int index) const;
  ::PROTOBUF_NAMESPACE_ID::Any* _internal_add_details();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Any& details(int index) const;
  ::PROTOBUF_NAMESPACE_ID::Any* add_details();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PROTOBUF_NAMESPACE_ID::Any >&
      details() const;

  // optional string message = 2;
  bool has_message() const;
  private:
  bool _internal_has_message() const;
  public:
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // .uprotocol.v1.UCode code = 1;
  void clear_code();
  ::uprotocol::v1::UCode code() const;
  void set_code(::uprotocol::v1::UCode value);
  private:
  ::uprotocol::v1::UCode _internal_code() const;
  void _internal_set_code(::uprotocol::v1::UCode value);
  public:

  // @@protoc_insertion_point(class_scope:uprotocol.v1.UStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PROTOBUF_NAMESPACE_ID::Any > details_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    int code_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ustatus_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UStatus

// .uprotocol.v1.UCode code = 1;
inline void UStatus::clear_code() {
  _impl_.code_ = 0;
}
inline ::uprotocol::v1::UCode UStatus::_internal_code() const {
  return static_cast< ::uprotocol::v1::UCode >(_impl_.code_);
}
inline ::uprotocol::v1::UCode UStatus::code() const {
  // @@protoc_insertion_point(field_get:uprotocol.v1.UStatus.code)
  return _internal_code();
}
inline void UStatus::_internal_set_code(::uprotocol::v1::UCode value) {
  
  _impl_.code_ = value;
}
inline void UStatus::set_code(::uprotocol::v1::UCode value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:uprotocol.v1.UStatus.code)
}

// optional string message = 2;
inline bool UStatus::_internal_has_message() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool UStatus::has_message() const {
  return _internal_has_message();
}
inline void UStatus::clear_message() {
  _impl_.message_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& UStatus::message() const {
  // @@protoc_insertion_point(field_get:uprotocol.v1.UStatus.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UStatus::set_message(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:uprotocol.v1.UStatus.message)
}
inline std::string* UStatus::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:uprotocol.v1.UStatus.message)
  return _s;
}
inline const std::string& UStatus::_internal_message() const {
  return _impl_.message_.Get();
}
inline void UStatus::_internal_set_message(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* UStatus::_internal_mutable_message() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* UStatus::release_message() {
  // @@protoc_insertion_point(field_release:uprotocol.v1.UStatus.message)
  if (!_internal_has_message()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.message_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void UStatus::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:uprotocol.v1.UStatus.message)
}

// repeated .google.protobuf.Any details = 3;
inline int UStatus::_internal_details_size() const {
  return _impl_.details_.size();
}
inline int UStatus::details_size() const {
  return _internal_details_size();
}
inline ::PROTOBUF_NAMESPACE_ID::Any* UStatus::mutable_details(int index) {
  // @@protoc_insertion_point(field_mutable:uprotocol.v1.UStatus.details)
  return _impl_.details_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PROTOBUF_NAMESPACE_ID::Any >*
UStatus::mutable_details() {
  // @@protoc_insertion_point(field_mutable_list:uprotocol.v1.UStatus.details)
  return &_impl_.details_;
}
inline const ::PROTOBUF_NAMESPACE_ID::Any& UStatus::_internal_details(int index) const {
  return _impl_.details_.Get(index);
}
inline const ::PROTOBUF_NAMESPACE_ID::Any& UStatus::details(int index) const {
  // @@protoc_insertion_point(field_get:uprotocol.v1.UStatus.details)
  return _internal_details(index);
}
inline ::PROTOBUF_NAMESPACE_ID::Any* UStatus::_internal_add_details() {
  return _impl_.details_.Add();
}
inline ::PROTOBUF_NAMESPACE_ID::Any* UStatus::add_details() {
  ::PROTOBUF_NAMESPACE_ID::Any* _add = _internal_add_details();
  // @@protoc_insertion_point(field_add:uprotocol.v1.UStatus.details)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PROTOBUF_NAMESPACE_ID::Any >&
UStatus::details() const {
  // @@protoc_insertion_point(field_list:uprotocol.v1.UStatus.details)
  return _impl_.details_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace uprotocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::uprotocol::v1::UCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::uprotocol::v1::UCode>() {
  return ::uprotocol::v1::UCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ustatus_2eproto
