// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uuid.proto

#include "uuid.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace uprotocol {
namespace v1 {
PROTOBUF_CONSTEXPR UUID::UUID(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.msb_)*/uint64_t{0u}
  , /*decltype(_impl_.lsb_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UUIDDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UUIDDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UUIDDefaultTypeInternal() {}
  union {
    UUID _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UUIDDefaultTypeInternal _UUID_default_instance_;
}  // namespace v1
}  // namespace uprotocol
static ::_pb::Metadata file_level_metadata_uuid_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_uuid_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_uuid_2eproto = nullptr;

const uint32_t TableStruct_uuid_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::uprotocol::v1::UUID, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::uprotocol::v1::UUID, _impl_.msb_),
  PROTOBUF_FIELD_OFFSET(::uprotocol::v1::UUID, _impl_.lsb_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::uprotocol::v1::UUID)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::uprotocol::v1::_UUID_default_instance_._instance,
};

const char descriptor_table_protodef_uuid_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nuuid.proto\022\014uprotocol.v1\" \n\004UUID\022\013\n\003ms"
  "b\030\001 \001(\006\022\013\n\003lsb\030\002 \001(\006B\'\n\030org.eclipse.upro"
  "tocol.v1B\tUUIDProtoP\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_uuid_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_uuid_2eproto = {
    false, false, 109, descriptor_table_protodef_uuid_2eproto,
    "uuid.proto",
    &descriptor_table_uuid_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_uuid_2eproto::offsets,
    file_level_metadata_uuid_2eproto, file_level_enum_descriptors_uuid_2eproto,
    file_level_service_descriptors_uuid_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_uuid_2eproto_getter() {
  return &descriptor_table_uuid_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_uuid_2eproto(&descriptor_table_uuid_2eproto);
namespace uprotocol {
namespace v1 {

// ===================================================================

class UUID::_Internal {
 public:
};

UUID::UUID(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:uprotocol.v1.UUID)
}
UUID::UUID(const UUID& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UUID* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.msb_){}
    , decltype(_impl_.lsb_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.msb_, &from._impl_.msb_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.lsb_) -
    reinterpret_cast<char*>(&_impl_.msb_)) + sizeof(_impl_.lsb_));
  // @@protoc_insertion_point(copy_constructor:uprotocol.v1.UUID)
}

inline void UUID::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.msb_){uint64_t{0u}}
    , decltype(_impl_.lsb_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

UUID::~UUID() {
  // @@protoc_insertion_point(destructor:uprotocol.v1.UUID)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UUID::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void UUID::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UUID::Clear() {
// @@protoc_insertion_point(message_clear_start:uprotocol.v1.UUID)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.msb_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.lsb_) -
      reinterpret_cast<char*>(&_impl_.msb_)) + sizeof(_impl_.lsb_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UUID::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // fixed64 msb = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _impl_.msb_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<uint64_t>(ptr);
          ptr += sizeof(uint64_t);
        } else
          goto handle_unusual;
        continue;
      // fixed64 lsb = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.lsb_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<uint64_t>(ptr);
          ptr += sizeof(uint64_t);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UUID::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:uprotocol.v1.UUID)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // fixed64 msb = 1;
  if (this->_internal_msb() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFixed64ToArray(1, this->_internal_msb(), target);
  }

  // fixed64 lsb = 2;
  if (this->_internal_lsb() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFixed64ToArray(2, this->_internal_lsb(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:uprotocol.v1.UUID)
  return target;
}

size_t UUID::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:uprotocol.v1.UUID)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // fixed64 msb = 1;
  if (this->_internal_msb() != 0) {
    total_size += 1 + 8;
  }

  // fixed64 lsb = 2;
  if (this->_internal_lsb() != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UUID::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UUID::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UUID::GetClassData() const { return &_class_data_; }


void UUID::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UUID*>(&to_msg);
  auto& from = static_cast<const UUID&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:uprotocol.v1.UUID)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_msb() != 0) {
    _this->_internal_set_msb(from._internal_msb());
  }
  if (from._internal_lsb() != 0) {
    _this->_internal_set_lsb(from._internal_lsb());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UUID::CopyFrom(const UUID& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:uprotocol.v1.UUID)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UUID::IsInitialized() const {
  return true;
}

void UUID::InternalSwap(UUID* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UUID, _impl_.lsb_)
      + sizeof(UUID::_impl_.lsb_)
      - PROTOBUF_FIELD_OFFSET(UUID, _impl_.msb_)>(
          reinterpret_cast<char*>(&_impl_.msb_),
          reinterpret_cast<char*>(&other->_impl_.msb_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UUID::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_uuid_2eproto_getter, &descriptor_table_uuid_2eproto_once,
      file_level_metadata_uuid_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace uprotocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::uprotocol::v1::UUID*
Arena::CreateMaybeMessage< ::uprotocol::v1::UUID >(Arena* arena) {
  return Arena::CreateMessageInternal< ::uprotocol::v1::UUID >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
