// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/utwin/v1/utwin.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_core_2futwin_2fv1_2futwin_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_core_2futwin_2fv1_2futwin_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "uprotocol_options.pb.h"
#include "ustatus.pb.h"
#include "uri.pb.h"
#include "umessage.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_core_2futwin_2fv1_2futwin_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_core_2futwin_2fv1_2futwin_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_core_2futwin_2fv1_2futwin_2eproto;
namespace uprotocol {
namespace core {
namespace utwin {
namespace v1 {
class GetLastEventResponse;
struct GetLastEventResponseDefaultTypeInternal;
extern GetLastEventResponseDefaultTypeInternal _GetLastEventResponse_default_instance_;
class GetLastEventsResponse;
struct GetLastEventsResponseDefaultTypeInternal;
extern GetLastEventsResponseDefaultTypeInternal _GetLastEventsResponse_default_instance_;
}  // namespace v1
}  // namespace utwin
}  // namespace core
}  // namespace uprotocol
PROTOBUF_NAMESPACE_OPEN
template<> ::uprotocol::core::utwin::v1::GetLastEventResponse* Arena::CreateMaybeMessage<::uprotocol::core::utwin::v1::GetLastEventResponse>(Arena*);
template<> ::uprotocol::core::utwin::v1::GetLastEventsResponse* Arena::CreateMaybeMessage<::uprotocol::core::utwin::v1::GetLastEventsResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace uprotocol {
namespace core {
namespace utwin {
namespace v1 {

// ===================================================================

class GetLastEventResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:uprotocol.core.utwin.v1.GetLastEventResponse) */ {
 public:
  inline GetLastEventResponse() : GetLastEventResponse(nullptr) {}
  ~GetLastEventResponse() override;
  explicit PROTOBUF_CONSTEXPR GetLastEventResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetLastEventResponse(const GetLastEventResponse& from);
  GetLastEventResponse(GetLastEventResponse&& from) noexcept
    : GetLastEventResponse() {
    *this = ::std::move(from);
  }

  inline GetLastEventResponse& operator=(const GetLastEventResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetLastEventResponse& operator=(GetLastEventResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetLastEventResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetLastEventResponse* internal_default_instance() {
    return reinterpret_cast<const GetLastEventResponse*>(
               &_GetLastEventResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GetLastEventResponse& a, GetLastEventResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetLastEventResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetLastEventResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetLastEventResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetLastEventResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetLastEventResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetLastEventResponse& from) {
    GetLastEventResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetLastEventResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "uprotocol.core.utwin.v1.GetLastEventResponse";
  }
  protected:
  explicit GetLastEventResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTopicFieldNumber = 1,
    kStatusFieldNumber = 2,
    kEventFieldNumber = 3,
  };
  // .uprotocol.v1.UUri topic = 1;
  bool has_topic() const;
  private:
  bool _internal_has_topic() const;
  public:
  void clear_topic();
  const ::uprotocol::v1::UUri& topic() const;
  PROTOBUF_NODISCARD ::uprotocol::v1::UUri* release_topic();
  ::uprotocol::v1::UUri* mutable_topic();
  void set_allocated_topic(::uprotocol::v1::UUri* topic);
  private:
  const ::uprotocol::v1::UUri& _internal_topic() const;
  ::uprotocol::v1::UUri* _internal_mutable_topic();
  public:
  void unsafe_arena_set_allocated_topic(
      ::uprotocol::v1::UUri* topic);
  ::uprotocol::v1::UUri* unsafe_arena_release_topic();

  // .uprotocol.v1.UStatus status = 2;
  bool has_status() const;
  private:
  bool _internal_has_status() const;
  public:
  void clear_status();
  const ::uprotocol::v1::UStatus& status() const;
  PROTOBUF_NODISCARD ::uprotocol::v1::UStatus* release_status();
  ::uprotocol::v1::UStatus* mutable_status();
  void set_allocated_status(::uprotocol::v1::UStatus* status);
  private:
  const ::uprotocol::v1::UStatus& _internal_status() const;
  ::uprotocol::v1::UStatus* _internal_mutable_status();
  public:
  void unsafe_arena_set_allocated_status(
      ::uprotocol::v1::UStatus* status);
  ::uprotocol::v1::UStatus* unsafe_arena_release_status();

  // .uprotocol.v1.UMessage event = 3;
  bool has_event() const;
  private:
  bool _internal_has_event() const;
  public:
  void clear_event();
  const ::uprotocol::v1::UMessage& event() const;
  PROTOBUF_NODISCARD ::uprotocol::v1::UMessage* release_event();
  ::uprotocol::v1::UMessage* mutable_event();
  void set_allocated_event(::uprotocol::v1::UMessage* event);
  private:
  const ::uprotocol::v1::UMessage& _internal_event() const;
  ::uprotocol::v1::UMessage* _internal_mutable_event();
  public:
  void unsafe_arena_set_allocated_event(
      ::uprotocol::v1::UMessage* event);
  ::uprotocol::v1::UMessage* unsafe_arena_release_event();

  // @@protoc_insertion_point(class_scope:uprotocol.core.utwin.v1.GetLastEventResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::uprotocol::v1::UUri* topic_;
    ::uprotocol::v1::UStatus* status_;
    ::uprotocol::v1::UMessage* event_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_core_2futwin_2fv1_2futwin_2eproto;
};
// -------------------------------------------------------------------

class GetLastEventsResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:uprotocol.core.utwin.v1.GetLastEventsResponse) */ {
 public:
  inline GetLastEventsResponse() : GetLastEventsResponse(nullptr) {}
  ~GetLastEventsResponse() override;
  explicit PROTOBUF_CONSTEXPR GetLastEventsResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetLastEventsResponse(const GetLastEventsResponse& from);
  GetLastEventsResponse(GetLastEventsResponse&& from) noexcept
    : GetLastEventsResponse() {
    *this = ::std::move(from);
  }

  inline GetLastEventsResponse& operator=(const GetLastEventsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetLastEventsResponse& operator=(GetLastEventsResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetLastEventsResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetLastEventsResponse* internal_default_instance() {
    return reinterpret_cast<const GetLastEventsResponse*>(
               &_GetLastEventsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GetLastEventsResponse& a, GetLastEventsResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetLastEventsResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetLastEventsResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetLastEventsResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetLastEventsResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetLastEventsResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetLastEventsResponse& from) {
    GetLastEventsResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetLastEventsResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "uprotocol.core.utwin.v1.GetLastEventsResponse";
  }
  protected:
  explicit GetLastEventsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResponsesFieldNumber = 2,
  };
  // repeated .uprotocol.core.utwin.v1.GetLastEventResponse responses = 2;
  int responses_size() const;
  private:
  int _internal_responses_size() const;
  public:
  void clear_responses();
  ::uprotocol::core::utwin::v1::GetLastEventResponse* mutable_responses(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::uprotocol::core::utwin::v1::GetLastEventResponse >*
      mutable_responses();
  private:
  const ::uprotocol::core::utwin::v1::GetLastEventResponse& _internal_responses(int index) const;
  ::uprotocol::core::utwin::v1::GetLastEventResponse* _internal_add_responses();
  public:
  const ::uprotocol::core::utwin::v1::GetLastEventResponse& responses(int index) const;
  ::uprotocol::core::utwin::v1::GetLastEventResponse* add_responses();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::uprotocol::core::utwin::v1::GetLastEventResponse >&
      responses() const;

  // @@protoc_insertion_point(class_scope:uprotocol.core.utwin.v1.GetLastEventsResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::uprotocol::core::utwin::v1::GetLastEventResponse > responses_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_core_2futwin_2fv1_2futwin_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetLastEventResponse

// .uprotocol.v1.UUri topic = 1;
inline bool GetLastEventResponse::_internal_has_topic() const {
  return this != internal_default_instance() && _impl_.topic_ != nullptr;
}
inline bool GetLastEventResponse::has_topic() const {
  return _internal_has_topic();
}
inline const ::uprotocol::v1::UUri& GetLastEventResponse::_internal_topic() const {
  const ::uprotocol::v1::UUri* p = _impl_.topic_;
  return p != nullptr ? *p : reinterpret_cast<const ::uprotocol::v1::UUri&>(
      ::uprotocol::v1::_UUri_default_instance_);
}
inline const ::uprotocol::v1::UUri& GetLastEventResponse::topic() const {
  // @@protoc_insertion_point(field_get:uprotocol.core.utwin.v1.GetLastEventResponse.topic)
  return _internal_topic();
}
inline void GetLastEventResponse::unsafe_arena_set_allocated_topic(
    ::uprotocol::v1::UUri* topic) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.topic_);
  }
  _impl_.topic_ = topic;
  if (topic) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:uprotocol.core.utwin.v1.GetLastEventResponse.topic)
}
inline ::uprotocol::v1::UUri* GetLastEventResponse::release_topic() {
  
  ::uprotocol::v1::UUri* temp = _impl_.topic_;
  _impl_.topic_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::uprotocol::v1::UUri* GetLastEventResponse::unsafe_arena_release_topic() {
  // @@protoc_insertion_point(field_release:uprotocol.core.utwin.v1.GetLastEventResponse.topic)
  
  ::uprotocol::v1::UUri* temp = _impl_.topic_;
  _impl_.topic_ = nullptr;
  return temp;
}
inline ::uprotocol::v1::UUri* GetLastEventResponse::_internal_mutable_topic() {
  
  if (_impl_.topic_ == nullptr) {
    auto* p = CreateMaybeMessage<::uprotocol::v1::UUri>(GetArenaForAllocation());
    _impl_.topic_ = p;
  }
  return _impl_.topic_;
}
inline ::uprotocol::v1::UUri* GetLastEventResponse::mutable_topic() {
  ::uprotocol::v1::UUri* _msg = _internal_mutable_topic();
  // @@protoc_insertion_point(field_mutable:uprotocol.core.utwin.v1.GetLastEventResponse.topic)
  return _msg;
}
inline void GetLastEventResponse::set_allocated_topic(::uprotocol::v1::UUri* topic) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.topic_);
  }
  if (topic) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(topic));
    if (message_arena != submessage_arena) {
      topic = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, topic, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.topic_ = topic;
  // @@protoc_insertion_point(field_set_allocated:uprotocol.core.utwin.v1.GetLastEventResponse.topic)
}

// .uprotocol.v1.UStatus status = 2;
inline bool GetLastEventResponse::_internal_has_status() const {
  return this != internal_default_instance() && _impl_.status_ != nullptr;
}
inline bool GetLastEventResponse::has_status() const {
  return _internal_has_status();
}
inline const ::uprotocol::v1::UStatus& GetLastEventResponse::_internal_status() const {
  const ::uprotocol::v1::UStatus* p = _impl_.status_;
  return p != nullptr ? *p : reinterpret_cast<const ::uprotocol::v1::UStatus&>(
      ::uprotocol::v1::_UStatus_default_instance_);
}
inline const ::uprotocol::v1::UStatus& GetLastEventResponse::status() const {
  // @@protoc_insertion_point(field_get:uprotocol.core.utwin.v1.GetLastEventResponse.status)
  return _internal_status();
}
inline void GetLastEventResponse::unsafe_arena_set_allocated_status(
    ::uprotocol::v1::UStatus* status) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.status_);
  }
  _impl_.status_ = status;
  if (status) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:uprotocol.core.utwin.v1.GetLastEventResponse.status)
}
inline ::uprotocol::v1::UStatus* GetLastEventResponse::release_status() {
  
  ::uprotocol::v1::UStatus* temp = _impl_.status_;
  _impl_.status_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::uprotocol::v1::UStatus* GetLastEventResponse::unsafe_arena_release_status() {
  // @@protoc_insertion_point(field_release:uprotocol.core.utwin.v1.GetLastEventResponse.status)
  
  ::uprotocol::v1::UStatus* temp = _impl_.status_;
  _impl_.status_ = nullptr;
  return temp;
}
inline ::uprotocol::v1::UStatus* GetLastEventResponse::_internal_mutable_status() {
  
  if (_impl_.status_ == nullptr) {
    auto* p = CreateMaybeMessage<::uprotocol::v1::UStatus>(GetArenaForAllocation());
    _impl_.status_ = p;
  }
  return _impl_.status_;
}
inline ::uprotocol::v1::UStatus* GetLastEventResponse::mutable_status() {
  ::uprotocol::v1::UStatus* _msg = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:uprotocol.core.utwin.v1.GetLastEventResponse.status)
  return _msg;
}
inline void GetLastEventResponse::set_allocated_status(::uprotocol::v1::UStatus* status) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.status_);
  }
  if (status) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(status));
    if (message_arena != submessage_arena) {
      status = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, status, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.status_ = status;
  // @@protoc_insertion_point(field_set_allocated:uprotocol.core.utwin.v1.GetLastEventResponse.status)
}

// .uprotocol.v1.UMessage event = 3;
inline bool GetLastEventResponse::_internal_has_event() const {
  return this != internal_default_instance() && _impl_.event_ != nullptr;
}
inline bool GetLastEventResponse::has_event() const {
  return _internal_has_event();
}
inline const ::uprotocol::v1::UMessage& GetLastEventResponse::_internal_event() const {
  const ::uprotocol::v1::UMessage* p = _impl_.event_;
  return p != nullptr ? *p : reinterpret_cast<const ::uprotocol::v1::UMessage&>(
      ::uprotocol::v1::_UMessage_default_instance_);
}
inline const ::uprotocol::v1::UMessage& GetLastEventResponse::event() const {
  // @@protoc_insertion_point(field_get:uprotocol.core.utwin.v1.GetLastEventResponse.event)
  return _internal_event();
}
inline void GetLastEventResponse::unsafe_arena_set_allocated_event(
    ::uprotocol::v1::UMessage* event) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.event_);
  }
  _impl_.event_ = event;
  if (event) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:uprotocol.core.utwin.v1.GetLastEventResponse.event)
}
inline ::uprotocol::v1::UMessage* GetLastEventResponse::release_event() {
  
  ::uprotocol::v1::UMessage* temp = _impl_.event_;
  _impl_.event_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::uprotocol::v1::UMessage* GetLastEventResponse::unsafe_arena_release_event() {
  // @@protoc_insertion_point(field_release:uprotocol.core.utwin.v1.GetLastEventResponse.event)
  
  ::uprotocol::v1::UMessage* temp = _impl_.event_;
  _impl_.event_ = nullptr;
  return temp;
}
inline ::uprotocol::v1::UMessage* GetLastEventResponse::_internal_mutable_event() {
  
  if (_impl_.event_ == nullptr) {
    auto* p = CreateMaybeMessage<::uprotocol::v1::UMessage>(GetArenaForAllocation());
    _impl_.event_ = p;
  }
  return _impl_.event_;
}
inline ::uprotocol::v1::UMessage* GetLastEventResponse::mutable_event() {
  ::uprotocol::v1::UMessage* _msg = _internal_mutable_event();
  // @@protoc_insertion_point(field_mutable:uprotocol.core.utwin.v1.GetLastEventResponse.event)
  return _msg;
}
inline void GetLastEventResponse::set_allocated_event(::uprotocol::v1::UMessage* event) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.event_);
  }
  if (event) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(event));
    if (message_arena != submessage_arena) {
      event = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, event, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.event_ = event;
  // @@protoc_insertion_point(field_set_allocated:uprotocol.core.utwin.v1.GetLastEventResponse.event)
}

// -------------------------------------------------------------------

// GetLastEventsResponse

// repeated .uprotocol.core.utwin.v1.GetLastEventResponse responses = 2;
inline int GetLastEventsResponse::_internal_responses_size() const {
  return _impl_.responses_.size();
}
inline int GetLastEventsResponse::responses_size() const {
  return _internal_responses_size();
}
inline void GetLastEventsResponse::clear_responses() {
  _impl_.responses_.Clear();
}
inline ::uprotocol::core::utwin::v1::GetLastEventResponse* GetLastEventsResponse::mutable_responses(int index) {
  // @@protoc_insertion_point(field_mutable:uprotocol.core.utwin.v1.GetLastEventsResponse.responses)
  return _impl_.responses_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::uprotocol::core::utwin::v1::GetLastEventResponse >*
GetLastEventsResponse::mutable_responses() {
  // @@protoc_insertion_point(field_mutable_list:uprotocol.core.utwin.v1.GetLastEventsResponse.responses)
  return &_impl_.responses_;
}
inline const ::uprotocol::core::utwin::v1::GetLastEventResponse& GetLastEventsResponse::_internal_responses(int index) const {
  return _impl_.responses_.Get(index);
}
inline const ::uprotocol::core::utwin::v1::GetLastEventResponse& GetLastEventsResponse::responses(int index) const {
  // @@protoc_insertion_point(field_get:uprotocol.core.utwin.v1.GetLastEventsResponse.responses)
  return _internal_responses(index);
}
inline ::uprotocol::core::utwin::v1::GetLastEventResponse* GetLastEventsResponse::_internal_add_responses() {
  return _impl_.responses_.Add();
}
inline ::uprotocol::core::utwin::v1::GetLastEventResponse* GetLastEventsResponse::add_responses() {
  ::uprotocol::core::utwin::v1::GetLastEventResponse* _add = _internal_add_responses();
  // @@protoc_insertion_point(field_add:uprotocol.core.utwin.v1.GetLastEventsResponse.responses)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::uprotocol::core::utwin::v1::GetLastEventResponse >&
GetLastEventsResponse::responses() const {
  // @@protoc_insertion_point(field_list:uprotocol.core.utwin.v1.GetLastEventsResponse.responses)
  return _impl_.responses_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace utwin
}  // namespace core
}  // namespace uprotocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_core_2futwin_2fv1_2futwin_2eproto
