name: C++ Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:  
  build:
    runs-on: ubuntu-latest
    
    #container:
    #  image: ghcr.io/username/repository/image:tag
    #  options: --user <user_id>:<group_id>
    #  credentials:
    #    username: ${{ github.actor }}
    #    password: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        ccompiler: [gcc-11]
        cppcompiler: [g++-11]

    env:
      CC: ${{ matrix.ccompiler }}
      CXX: ${{ matrix.cppcompiler }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Compiler and Tools
      run: |
        sudo apt-update -y sudo apt-get -y upgrade && apt-get -y install g++ git libstdc++-11-dev
        sudo apt-get install -y g++-11 gcc-11
        sudo apt-get -y update && sudo apt-get install -y build-essential libbsd-dev make ninja-build pkg-config clang-format cmake gcc uuid uuid-dev openssl libssl-dev
        sudo apt-get install -y libgtest-dev rapidjson-dev cgreen1  libspdlog-dev libcgreen1-dev wget libprotobuf-dev
    - name: Update Cmake to latest version.
      run: |
        sudo apt-get install ca-certificates gpg wget
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
        echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
        sudo apt-get -y update && sudo apt-get -y install kitware-archive-keyring cmake
 
    - name: Build Protocol Buffer.
      run: |
        git clone --progress https://github.com/protocolbuffers/protobuf
        sudo ldconfig -v
        cd protobuf
        git submodule update --init --recursive
        cmake . -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_CXX_STANDARD=14  -DCMAKE_BUILD_TYPE=Debug -Dprotobuf_BUILD_SHARED_LIBS=ON -Dprotobuf_BUILD_TESTS=OFF;
        cmake --build . && sudo -E make -j4 install
        
        
    - name: Build C++ Application
      run: |
        mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ../CMakeLists.txt --no-warn-unused-cli && make -j4
        
    - name: Run Test Capture
      run: |
        cd build
        ctest --verbose
        lcov --directory . --capture --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --list coverage.info
  
    - name: Check Code Coverage Threashold
      run: |
        COVERAGE_THRESHOLD=80
        COVERAGE_PERCENT=$(lcov --summary coverage.info | grep "lines......:" | awk '{print $3}')
        echo "Code coverage: $COVERAGE_PERCENT%"
        if [ $COVERAGE_PERCENT -lt $COVERAGE_THRESHOLD ]; then
          echo "Code coverage is below the threshold of $COVERAGE_THRESHOLD%"
          exit 1
        fi

